# config file for two nodes - path is /etc/prometheus/prometheus.yml 
global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['184.73.38.173:9100']  # Replace 'node_server_ip' with the actual IP of your node server
